[project]
name = "multimodal-agentic-retrieval-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "easyocr>=1.7.2",
    "librosa>=0.11.0",
    "nemo-toolkit[asr]>=2.7.3",
    "soundfile>=0.14.0",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
]
