"""System 1 scenes package."""

__all__ = []
from .grouping import (
    BoundaryDecision,
    BoundaryVote,
    FocusWindow,
    SceneBoundaryJudge,
    SceneGroupingResult,
    ScenePartitionQuality,
    ScenePartitionQualityError,
    assess_partition_quality,
    group_scenes,
    partition_scenes,
    plan_focus_windows,
    vote_weight,
)
from .speech import (
    SpeechGapEvidence,
    build_speech_gap_evidence,
    render_speech_evidence,
    speech_diagnostics,
    validate_speech_policy,
)
from .summary import (
    AUDIO_VISUAL_RELATIONS,
    MODEL_AUDIO_VISUAL_RELATIONS,
    SPEECH_EVIDENCE_STATUSES,
    SpeechSummaryEvidence,
    VisualSummaryEvidence,
    build_speech_summary_evidence,
    build_visual_summary_evidence,
    classify_speech_evidence_status,
    normalize_audio_visual_relation,
    validate_scene_summary_policy,
    validate_scene_summary_semantics,
)

__all__ = [
    "BoundaryDecision",
    "BoundaryVote",
    "FocusWindow",
    "SceneBoundaryJudge",
    "SceneGroupingResult",
    "ScenePartitionQuality",
    "ScenePartitionQualityError",
    "SpeechSummaryEvidence",
    "SpeechGapEvidence",
    "VisualSummaryEvidence",
    "AUDIO_VISUAL_RELATIONS",
    "MODEL_AUDIO_VISUAL_RELATIONS",
    "SPEECH_EVIDENCE_STATUSES",
    "assess_partition_quality",
    "build_speech_gap_evidence",
    "build_speech_summary_evidence",
    "build_visual_summary_evidence",
    "classify_speech_evidence_status",
    "group_scenes",
    "partition_scenes",
    "plan_focus_windows",
    "render_speech_evidence",
    "normalize_audio_visual_relation",
    "speech_diagnostics",
    "validate_speech_policy",
    "validate_scene_summary_policy",
    "validate_scene_summary_semantics",
    "vote_weight",
]
